apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../namespaces/namespace.yaml
  - ../app/03-mysql_pvc.yaml
  - ../app/04-mysql_deployment.yaml
  - ../app/05-mysql_service.yaml
  - ../app/06-config-map.yaml
  - ../app/07-appdeployment.yaml
  - ../app/08-service.yaml